#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// 

#include <bit>
#include "UnrealContainers.hpp"

namespace UC::FMemory
{
	FMalloc* GMalloc{};
	FMalloc** FMalloc::UnrealStaticGMalloc{};

	void* FMalloc::Malloc(uint64 Count, uint32 Alignment) {
		std::byte* vtable = std::bit_cast<std::byte*>(*std::bit_cast<std::byte**>(this));
		auto func = std::bit_cast<void* (FMalloc::*)(uint64, uint32) const>(*std::bit_cast<void**>(vtable + 0x28));
		return (this->*func)(Count, Alignment);
	};
	void* FMalloc::Realloc(void* Original, uint64 Count, uint32 Alignment) {
		std::byte* vtable = std::bit_cast<std::byte*>(*std::bit_cast<std::byte**>(this));
		auto func = std::bit_cast<void* (FMalloc::*)(void*, uint64, uint32) const>(*std::bit_cast<void**>(vtable + 0x38));
		return (this->*func)(Original, Count, Alignment);
	};
	void FMalloc::Free(void* Original) {
		std::byte* vtable = std::bit_cast<std::byte*>(*std::bit_cast<std::byte**>(this));
		auto func = std::bit_cast<void(FMalloc::*)(void*) const>(*std::bit_cast<void**>(vtable + 0x48));
		(this->*func)(Original);
	};
}

